routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use App\User;

Route::get('/', function () {
    if (Auth::check()) {
        return redirect()->route('home_redirect');
    }
    return redirect()->route('login');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/documents/unreceive', 'DocumentUnreceiveController')->middleware('can:view inbox unreceive menu');
Route::post('documents/unreceive/{unreceive}/reject', 'RejectDocumentController')->name('unreceive.reject');
Route::post('documents/unreceive/{unreceive}/accept', 'AcceptDocumentController')->name('unreceive.accept');

Route::resource('/documents/receive', 'DocumentReceiveController')->middleware('can:view inbox receive menu');
Route::resource('/documents/reject', 'DocumentRejectController')->middleware('can:view inbox reject menu');

Route::resource('/documents/unsend', 'DocumentUnsendController')->middleware('can:view outbox unsend menu');
Route::post('documents/unsend/{unsend}/reject', 'RejectUnsendDocumentController')->name('unsend.reject');
Route::post('documents/unsend/{unsend}/accept', 'AcceptUnsendDocumentController')->name('unsend.accept');

Route::post('documents/helper/validate_receive_number', 'ValidationHelperController@isValidReceiveNumber')->name('helper.validate_receive_number');

Route::resource('/documents/send', 'DocumentSendController')->middleware('can:view outbox send menu');

Route::resource('/documents/reject-send', 'DocumentSendRejectController')->middleware('can:view outbox reject-send menu');

Route::get('/documents/search', 'SearchController@index')->name('search')->middleware('can:view search menu');
Route::get('/documents/search/result', 'SearchController@search')->name('result');

Route::get('/typeahead-search/{pid}', 'TypeAheadSearchController@search');



Route::get('/modal', function () {
    return view('layouts.shared.modals.modal');
});


Route::get('/notify', function () {
    // $user = Auth::user();

    // $user->notify(new SendDocument(User::findOrFail(3)));
    \Notification::send(User::all(), new SendDocument());

    // foreach (Auth::user()->notifications as $notification) {
    //     dd($notification);
    // }
});

Route::get('/sentnotify/{id}', 'AcceptUnsendDocumentController@sentNotify');

Route::get('/read/{id}', function ($id) {
    auth()->user()->unreadNotifications->find($id)->markAsRead();

    $notification = auth()->user()->unreadNotifications->find($id);

    return back();
})->name('notification.read');

Route::resource('/system_manage/user', 'UserManageController')->middleware('can:view user manage menu');
Route::resource('/system_manage/role', 'RoleManageController')->middleware('can:view role menu');
Route::resource('/profile', 'ProfileController');

Route::post('/ajax/delete-attachment', 'AjaxController@deleteAttachment')->name('ajax.delete_attachment');

Route::get('/documents', 'RedirectWithRoleController')->name('home_redirect');

Route::get('/documents/tag/{tag}', 'SearchController@search')->name('tag');

Route::get('/thakam-passport/redirect', 'ThakamPassportAuthController@redirect');
Route::get('/thakam-passport/callback', 'ThakamPassportAuthController@callback');

Route::view('/user-denied', 'user_denied');

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;


class Document extends Model
{
    protected $table = 'documents';

    protected $casts = [
        'attachment' => 'array',
        'keyword' => 'array',
        'document_destination' => 'array'
    ];

    private function toThaiNumber($number)
    {
        $numthai = array("๑", "๒", "๓", "๔", "๕", "๖", "๗", "๘", "๙", "๐");
        $numarabic = array("1", "2", "3", "4", "5", "6", "7", "8", "9", "0");
        $str = str_replace($numarabic, $numthai, $number);
        return $str;
    }

    public function getDocumentNumberThaiAttribute()
    {
        return $this->toThaiNumber($this->document_number);
    }

    public function getDocumentRejectDateThaiAttribute()
    {
        return $this->toThaiNumber($this->document_reject_date);
    }

    public function getDocumentCreatedDateThaiAttribute()
    {
        return $this->toThaiNumber($this->document_created_date);
    }

    public function getDocumentAcceptDateThaiAttribute()
    {
        return $this->toThaiNumber($this->document_accept_date);
    }

    public function priority()
    {
        return $this->hasOne(Priority::class, 'id', 'priority_id');
    }

    public function progress()
    {
        return $this->hasOne(Progress::class, 'id', 'document_progress_id');
    }

    public function purpose()
    {
        return $this->hasOne(Purpose::class, 'id', 'purpose_id');
    }

    public function type()
    {
        return $this->hasOne(Type::class, 'id', 'type_id');
    }

    public function folder()
    {
        return $this->hasOne(Folder::class, 'id', 'folder_id');
    }

    public function secretLevel()
    {
        return $this->hasOne(SecreteLevel::class, 'id', 'secret_level_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'document_create_by_user_id', 'id');
    }

    public function userAction()
    {
        return $this->belongsTo(User::class, 'document_action_by_user_id', 'id');
    }

    public function scopeUnreceive($query)
    {
        return $query->where('document_progress_id', 1);
    }

    public function scopeUnsend($query)
    {
        return $query->where('document_progress_id', 2);
    }

    public function scopeReceive($query)
    {
        return $query->where('document_progress_id', 3);
    }

    public function scopeSend($query)
    {
        return $query->where('document_progress_id', 5);
    }

    public function scopeReject($query)
    {
        return $query->where('document_progress_id', 4);
    }

    public function scopeSendReject($query)
    {
        return $query->where('document_progress_id', 6);
    }

    public function scopeInbox($query)
    {
        return $query->where('folder_id', 1);
    }

    public function scopeOutbox($query)
    {
        return $query->where('folder_id', 2);
    }

    public function getSecretAttribute()
    {
        $allPermissions = [];
        $allSecretlevels = [
            '1' => 'view nomal document',
            '2' => 'view top secret document',
            '3' => 'view secret document',
            '4' => 'view confidential document',
            '5' => 'view conceal document'
        ];

        $documentSecretLevels = $allSecretlevels[$this->secret_level_id];

        if (Auth::check()) {
            $uid = Auth::user()->id;
        }

        $user = User::find($uid);


        foreach ($user->getAllPermissions() as $permissions) {
            array_push($allPermissions, $permissions->name);
        }

        if (in_array($documentSecretLevels, $allPermissions)) {
            return true;
        }
        return false;
    }


    // public function getUnreceiveCountAttribute()
    // {
    //     if ($this->unreceive()->count() > 0) {
    //         return $this->unreceive()->count();
    //     }
    // }

    // public function getUnsendCountAttribute()
    // {
    //     if ($this->unsend()->count() > 0) {
    //         return $this->unsend()->count();
    //     }
    // }

    public function getSecretClassAttribute()
    {
        switch ($this->secret_level_id) {
            case '1':
                return "label bg-green";
                break;
            case '5':
                return "label bg-blue";
                break;
            case '4':
                return "label bg-yellow";
                break;
            case '3':
                return "label bg-orange";
                break;
            case '2':
                return "label bg-red";
                break;
            default:
                return "";
        }
    }

    public function attachments()
    {
        return $this->hasMany(Attachment::class);
    }

    public function getReceivedNumberAttribute()
    {
        if (!empty($this->receive_number)) {
            $receiveNumberWithYear = $this->receive_number;
            $receiveNumber = explode("_", $receiveNumberWithYear);

            return $receiveNumber[0];
        }

        return null;
    }
}

resources/views/outbox/unsend/create.blade.php
@extends('layouts.master')

@section('title')
สร้างหนังสือรอลงทะเบียนส่ง
@endsection

@section('header')
@include('layouts.shared._contentHeader', ['title' => 'สร้างหนังสือรอลงทะเบียนส่ง'])
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <form action="{{ route('unsend.store') }}" method="POST" class="form-horizontal"
                enctype="multipart/form-data">
                @include('outbox.unsend._form', ['buttonText' => "เพิ่มหนังสือรอลงทะเบียนส่ง"])
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/outbox/unsend/edit.blade.php
@extends('layouts.master')

@section('title')
แก้ไขหนังสือรอลงทะเบียนส่ง
@endsection

@section('header')
@include('layouts.shared._contentHeader', ['title' => 'แก้ไขหนังสือรอลงทะเบียนส่ง'])
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <form action="{{ route('unsend.update', $document->id) }}" method="POST" class="form-horizontal"
                enctype="multipart/form-data">
                {{ method_field('PATCH') }}
                @include('outbox.unsend._form', ['buttonText' => "แก้ไขหนังสือรอลงทะเบียนส่ง"])
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/outbox/unsend/index.blade.php
@extends('layouts.master')

@section('title')
หนังสือรอลงทะเบียนส่ง
@endsection

@section('header')
@include('layouts.shared._contentHeader', ['title' => 'หนังสือรอลงทะเบียนส่ง'])
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header">
                @can('create document')
                <a href="{{ route('unsend.create') }}" class="btn btn-default">สร้างหนังสือใหม่</a>
                @endcan
                <div class="box-tools">
                    <form action="/documents/search/result" method="GET">
                        <div class="input-group input-group-sm hidden-xs" style="width: 250px;">
                            <input type="text" name="subject" class="form-control search-box pull-right"
                                placeholder="สืบค้นหนังสือ">

                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th style="width: 10px" class="text-center">#</th>
                            <th class="text-center">เลขที่หนังสือ</th>
                            <th class="text-center">ลงวันที่</th>
                            <th class="text-center">ชั้นความสำคัญ</th>
                            <th class="text-center">ชั้นความลับ</th>
                            <th class="text-center">เรื่อง</th>
                            <th class="text-center">เอกสารแนบ</th>
                            @canany(['accept document', 'reject document'])
                            <th class="text-center">ลงทะเบียนส่ง / ตีกลับ</th>
                            @endcanany
                            <th class="text-center">รายละเอียดเพิ่มเติม</th>
                            @canany(['edit document', 'delete document'])
                            <th class="text-center">แก้ไข / ลบ</th>
                            @endcanany
                        </tr>
                        @if (count($documents) == 0)
                        <tr>
                            <td colspan="10" class="text-center">ไม่มีหนังสือที่รอลงทะเบียนส่ง</td>
                        </tr>
                        @else
                        @foreach ($documents as $document)
                        <tr>
                            <td class="text-center">{{$loop->iteration}}</td>
                            <td class="text-center">{{$document->document_number_thai}}</td>
                            <td class="text-center">{{$document->document_created_date_thai}}</td>
                            <td class="text-center">{{$document->priority->priority_name}}</td>
                            <td class="text-center {{ $document->secret_class }}">
                                {{$document->secretLevel->secret_level_name}}</td>
                            <td class="text-center">@if ($document->secret)
                                <strong>{{$document->subject}}</strong>
                                @else
                                <span class="text-red" title="เอกสารที่คุณไม่มีสิทธิ์เข้าถึง"><i
                                        class="fa fa-expeditedssl" style="color: #ffb300"
                                        title="เอกสารที่คุณไม่มีสิทธิ์เข้าถึง"></i>
                                    เอกสารที่คุณไม่มีสิทธิ์เข้าถึง</span>
                                @endif</td>

                            <td>
                                @if (count($document->attachments) == 0)
                                <p>ไม่มีเอกสารแนบ</p>
                                @else

                                @if ($document->secret)
                                @foreach ($document->attachments as $attachment)
                                <a href="{{ asset('/uploads/documents') . '/' . $attachment['store_name'] }}"
                                    style="display:block"><i class="fa fa-file-pdf-o"></i>
                                    {{ $attachment['original_name'] }}</a>
                                @endforeach

                                @else
                                @foreach ($document->attachments as $attachment)
                                <i class="fa fa-expeditedssl" style="color: #ffb300"
                                    title="เอกสารแนบที่คุณไม่มีสิทธิ์เข้าถึง"></i>
                                <a href="#" style="display:block" title="เอกสารแนบที่คุณไม่มีสิทธิ์เข้าถึง"><i
                                        class="fa fa-file-pdf-o"></i>
                                    เอกสารแนบที่คุณไม่มีสิทธิ์เข้าถึง [{{ $loop->iteration }}]</a>
                                @endforeach
                                @endif

                                @endif
                            </td>


                            @canany(['accept document', 'reject document'])
                            <td class="text-center">
                                <div>@can('accept document')<a href="#" class="accept-link" data-toggle="modal"
                                        data-target="#modal-accept" data-id="{{$document->id}}"
                                        data-number="{{ $document->document_number }}">ลงทะเบียนส่ง</a>@endcan /
                                    @can('reject document')<a href="#" class="reject-link" data-toggle="modal"
                                        data-target="#modal-reject" data-id="{{$document->id}}"
                                        data-number="{{$document->document_number}}"
                                        data-source="{{$document->document_source}}">ตีกลับ</a>@endcan</div>
                            </td>
                            @endcanany


                            <td class="text-center">
                                @if ($document->secret)
                                <a href="{{ route('unsend.show', $document->id) }}">รายละเอียดเพิ่มเติม</a>
                                @else
                                <a href="#" title="เอกสารที่คุณไม่มีสิทธิ์เข้าถึง"><i class="fa fa-expeditedssl"
                                        style="color: #ffb300" title="เอกสารที่คุณไม่มีสิทธิ์เข้าถึง"></i>
                                    รายละเอียดเพิ่มเติม</a>
                                @endif
                            </td>


                            @canany(['edit document', 'delete document'])
                            <td class="text-center">
                                @can('edit document')
                                <a href="{{ route('unsend.edit', $document->id) }}" class="btn btn-default btn-xs">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                @endcan
                                @can('delete document')
                                <a href="#" class="btn btn-default btn-xs delete-link" data-toggle="modal"
                                    data-target="#modal-delete" data-id="{{$document->id}}"
                                    data-number="{{ $document->document_number }}">
                                    <i class=" fa fa-trash"></i>
                                </a>
                                @endcan
                            </td>
                            @endcanany

                        </tr>
                        @endforeach
                        @endif
                    </tbody>
                </table>
            </div>

            <!-- Modal -->
            @include('layouts.shared.modals._reject')
            @include('layouts.shared.modals._accept')
            @include('layouts.shared.modals._delete')


            <!-- /.box-body -->
            <div class="box-footer clearfix">
                {{-- <ul class="pagination pagination-sm no-margin pull-right">
                    <li><a href="#">«</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">»</a></li>
                </ul> --}}
                <div class="pull-right">
                    {{ $documents->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    $( document ).ready(function() {
            $(document).on("click", ".reject-link", function () {
                var document_id = $(this).data('id');
                var document_number = $(this).data('number');
                var document_source = $(this).data('source');
                // var document_destination = $(this).data('destination');

                $('#reject-form').attr('action', '/documents/unsend/' + document_id + '/reject');
                $('.modal-title').text('ตีกลับหนังสือ');
                $('#reject-modal-source-content').text(document_source);
                // $('#reject-modal-destination-content').text(document_destination);
                $('#reject-modal-number-content').text(document_number);
        });
    });
</script>
<script>
    $( document ).ready(function() {
            $(document).on("click", ".accept-link", function () {
                var document_id = $(this).data('id');
                var document_number = $(this).data('number');

                $('#accept-form').attr('action', '/documents/unsend/' + document_id + '/accept');
                $('.modal-title').text('ลงทะเบียนส่งหนังสือ');
                $('#accept-modal-number-content').html('<strong>ยืนยัน</strong>การลงทะเบียนส่งหนังสือหมายเลข ' + document_number);   
                $('#accept-btn').text('ลงทะเบียนส่งหนังสือ');             
        });
    });
</script>
<script>
    $( document ).ready(function() {
            $(document).on("click", ".delete-link", function () {
                var document_id = $(this).data('id');
                var document_number = $(this).data('number');

                $('#delete-form').attr('action', '/documents/unsend/' + document_id);
                $('.modal-title').text('ลบหนังสือ');
                $('#delete-modal-number-content').html('<strong>ยืนยัน</strong>การลบหนังสือหมายเลข ' + document_number);                
        });
    });
</script>
<script>
    $(document).ready(function () {
                    var documents_suggestions = new Bloodhound({
                        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
                        queryTokenizer: Bloodhound.tokenizers.whitespace,
                        remote: {
                            url: '/typeahead-search/2/?keyword=%QUERY',
                            wildcard: '%QUERY' // %QUERY will be replace by users input in
                        }, // the url option.
                    });
            
                    // init Typeahead
                    $('.search-box').typeahead({
                        minLength: 1,
                        highlight: true
                    }, {
                        name: 'documents',
                        source: documents_suggestions,
                        display: function (item) {
                            return item.subject;
                        },
                        limit: 5,
                        templates: {
                            suggestion: function (item) {
                                return '<div><a href="/documents/receive/' + item.id + '">' + item.subject + '</a></div>'
                            }
                        }
                    });
                }); 
</script>
@endsection

resources/views/outbox/unsend/show.blade.php
@extends('layouts.master')

@section('title')
รายละเอียดหนังสือเลขที่ {{ $document->document_number }}
@endsection

@section('header')
@include('layouts.shared._contentHeader', ['title' => 'รายละเอียดหนังสือเลขที่ ' . $document->document_number])
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="box">

            <div class="box-body table-responsive no-padding">
                <div class="col-md-10 col-md-offset-1">
                    <br />
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <td><strong>เลขที่หนังสือ</strong></td>
                                <td>{{ $document->document_number }}</td>
                            </tr>
                            <tr>
                                <td><strong>ชั้นความสำคัญ</strong></td>
                                <td>{{ $document->priority->priority_name }}</td>
                            </tr>
                            <tr>
                                <td><strong>ชั้นความลับ</strong></td>
                                <td>{{ $document->secretLevel->secret_level_name }}</td>
                            </tr>
                            <tr>
                                <td><strong>เรื่อง</strong></td>
                                <td><strong>{{ $document->subject }}</strong></td>
                            </tr>
                            <tr>
                                <td><strong>ประเภทหนังสือ</strong></td>
                                <td>{{ $document->type->type_name }}</td>
                            </tr>
                            <tr>
                                <td><strong>เอกสารแนบ</strong></td>
                                <td>@if (count($document->attachments) == 0)
                                    <p>ไม่มีเอกสารแนบ</p>
                                    @else
                                    {{-- <a href="{{$document->attachment}}"><i class="fa fa-file-pdf-o"></i>
                                    ดาวน์โหลด</a> --}}
                                    @foreach ($document->attachments as $attachment)
                                    <a href="{{ asset('/uploads/documents') . '/' . $attachment['store_name'] }}"
                                        style="display:block"><i class="fa fa-file-pdf-o"></i>
                                        {{ $attachment['original_name'] }}</a>
                                    @endforeach
                                    @endif</td>
                            </tr>
                            <tr>
                                <td><strong>ลงวันที่</strong></td>
                                <td>{{ $document->document_created_date }}</td>
                            </tr>
                            <tr>
                                <td><strong>จากหน่วยงาน</strong></td>
                                <td>{{ $document->document_source }}</td>
                            </tr>
                            <tr>
                                <td><strong>เรียน / ถึง</strong></td>
                                {{-- <td>{{ $document->document_destination }}</td> --}}
                                <td>
                                    @if (empty($document->document_destination))
                                    <span></span>
                                    @else
                                    @foreach ($document->document_destination as $document_destination)
                                    <span>{{ $document_destination }}</span>
                                    @if (!$loop->last)
                                    ,
                                    @endif
                                    @endforeach
                                    @endif
                                </td>
                            </tr>
                            {{-- <tr>
                                <td><strong>การปฏิบัติ</strong></td>
                                <td>{{ $document->purpose->purpose_name }}</td>
                            </tr> --}}
                            <tr>
                                <td><strong>แท็ก</strong></td>
                                <td>
                                    @if (empty($document->keyword))
                                    <span></span>
                                    @else
                                    @foreach ($document->keyword as $keyword)
                                    <a href="/documents/tag/{{ $keyword }}" target="_blank" class="label bg-navy"
                                        style="display: inline">{{ $keyword }}</a>
                                    @endforeach
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <td><strong>หมายเหตุ</strong></td>
                                <td>{!! $document->annotation !!}</td>
                            </tr>
                        </tbody>
                    </table>
                    <a href="{{ route('unsend.index') }}" class="btn btn-primary btn-block">กลับหน้ารายการหนังสือ</a>
                    <br />
                </div>
            </div>
        </div>
    </div>
</div>
@endsection