routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use App\User;

Route::get('/', function () {
    if (Auth::check()) {
        return redirect()->route('home_redirect');
    }
    return redirect()->route('login');
});

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/documents/unreceive', 'DocumentUnreceiveController')->middleware('can:view inbox unreceive menu');
Route::post('documents/unreceive/{unreceive}/reject', 'RejectDocumentController')->name('unreceive.reject');
Route::post('documents/unreceive/{unreceive}/accept', 'AcceptDocumentController')->name('unreceive.accept');

Route::resource('/documents/receive', 'DocumentReceiveController')->middleware('can:view inbox receive menu');
Route::resource('/documents/reject', 'DocumentRejectController')->middleware('can:view inbox reject menu');

Route::resource('/documents/unsend', 'DocumentUnsendController')->middleware('can:view outbox unsend menu');
Route::post('documents/unsend/{unsend}/reject', 'RejectUnsendDocumentController')->name('unsend.reject');
Route::post('documents/unsend/{unsend}/accept', 'AcceptUnsendDocumentController')->name('unsend.accept');

Route::post('documents/helper/validate_receive_number', 'ValidationHelperController@isValidReceiveNumber')->name('helper.validate_receive_number');

Route::resource('/documents/send', 'DocumentSendController')->middleware('can:view outbox send menu');

Route::resource('/documents/reject-send', 'DocumentSendRejectController')->middleware('can:view outbox reject-send menu');

Route::get('/documents/search', 'SearchController@index')->name('search')->middleware('can:view search menu');
Route::get('/documents/search/result', 'SearchController@search')->name('result');

Route::get('/typeahead-search/{pid}', 'TypeAheadSearchController@search');



Route::get('/modal', function () {
    return view('layouts.shared.modals.modal');
});


Route::get('/notify', function () {
    // $user = Auth::user();

    // $user->notify(new SendDocument(User::findOrFail(3)));
    \Notification::send(User::all(), new SendDocument());

    // foreach (Auth::user()->notifications as $notification) {
    //     dd($notification);
    // }
});

Route::get('/sentnotify/{id}', 'AcceptUnsendDocumentController@sentNotify');

Route::get('/read/{id}', function ($id) {
    auth()->user()->unreadNotifications->find($id)->markAsRead();

    $notification = auth()->user()->unreadNotifications->find($id);

    return back();
})->name('notification.read');

Route::resource('/system_manage/user', 'UserManageController')->middleware('can:view user manage menu');
Route::resource('/system_manage/role', 'RoleManageController')->middleware('can:view role menu');
Route::resource('/profile', 'ProfileController');

Route::post('/ajax/delete-attachment', 'AjaxController@deleteAttachment')->name('ajax.delete_attachment');

Route::get('/documents', 'RedirectWithRoleController')->name('home_redirect');

Route::get('/documents/tag/{tag}', 'SearchController@search')->name('tag');

Route::get('/thakam-passport/redirect', 'ThakamPassportAuthController@redirect');
Route::get('/thakam-passport/callback', 'ThakamPassportAuthController@callback');

Route::view('/user-denied', 'user_denied');

resources/views/layouts/shared/_contentHeader.blade.php
<section class="content-header">
    <h1>
        {{ $title ?? 'untitled' }}
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">{{ $title ?? 'untitled' }}</li>
    </ol>
</section>

resources/views/layouts/shared/_footer.blade.php
<footer class="main-footer">
    {{-- <div class="pull-right hidden-xs">
        <b>Version</b> 2.4.18-pre
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE</a>.</strong> All rights
    reserved. --}}
    <span>ระบบสารบรรณอิเล็กทรอนิกส์ องค์การบริหารส่วนตำบลท่าข้าม</span>
</footer>

resources/views/layouts/shared/_header.blade.php
<header class="main-header">
  <!-- Logo -->
  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>E</b>OC</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>E - Office</b></span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown messages-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-envelope-o"></i>
            <span class="label label-success">{{ count(auth()->user()->unreadNotifications) }}</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">คุณมีเอกสาร {{ count(auth()->user()->unreadNotifications) }} ฉบับ</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                @foreach (auth()->user()->unreadNotifications as $notification)
                <li>
                  <a href="{{ route('notification.read', $notification->id) }}">
                    <div class="pull-left">
                      @if ($notification->data['folder'] == '1')
                      <i class="fa fa-download"></i>
                      @elseif($notification->data['folder'] == '2')
                      <i class="fa fa-upload"></i>
                      @endif

                    </div>
                    <h4>
                      {{ str_limit($notification->data['subject'], 25) }}
                      {{-- <small><i class="fa fa-clock-o"></i> 5 mins</small> --}}
                    </h4>
                    @php
                    $progressMatch = [
                    "1" => "unreceive",
                    "2" => "unsend",
                    "3" => "receive",
                    "4" => "reject",
                    "5" => "send",
                    "6" => "reject-send"
                    ]
                    @endphp
                    <p><span
                        class="pull-left">{{ \Carbon\Carbon::parse($notification->created_at)->diffForHumans() }}</span>
                      <a class="pull-right"
                        href="/documents/{{$progressMatch[$notification->data['progress']]}}/{{ $notification->data['did'] }}"
                        target="_blank"><strong>อ่าน</strong></a>
                    </p>
                  </a>
                </li>
                @endforeach


              </ul>
            </li>
            {{-- <li class="footer"><a href="#">See All Messages</a></li> --}}
          </ul>
        </li>
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="{{ asset('/uploads/avatar') }}/{{Auth()->user()->avatar ?? 'user-icon.png'}}" class="user-image"
              alt="User Image">
            <span class="hidden-xs">{{ Auth::user()->name }}</span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <img src="{{ asset('/uploads/avatar') }}/{{Auth()->user()->avatar ?? 'user-icon.png'}}" class="img-circle"
                alt="User Image">

              <p>
                {{ Auth::user()->name }} -
                @foreach (Auth()->user()->getRoleNames() as $role)
                {{ strtoupper($role) }}
                @endforeach
                {{-- <small>Member since Nov. 2012</small> --}}
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="{{ route('profile.edit', Auth::User()->id) }}" class="btn btn-default btn-flat">โปรไฟล์</a>
              </div>
              <div class="pull-right">
                <a href="{{ route('logout') }}" onclick="event.preventDefault();
                  document.getElementById('logout-form').submit();" class="btn btn-default btn-flat">ออกจากระบบ</a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  @csrf
                </form>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

resources/views/layouts/shared/_modal.blade.php
<div class="modal fade" id="modal-default">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">{{ $title }}</h4>
            </div>
            <div class="modal-body">
                {{ $body }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">{{ $buttonText }}</button>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/shared/_sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset('/uploads/avatar') }}/{{Auth()->user()->avatar ?? 'user-icon.png'}}"
                    class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ Auth()->user()->name }}</p>
                <a href="#">
                    @foreach (Auth()->user()->getRoleNames() as $roleName)
                    <li>{{ strtoupper($roleName) }}</li>
                    @endforeach
                </a>
            </div>
        </div>
        <!-- search form -->
        <form action="{{ route('result') }}" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="subject" class="form-control" placeholder="ค้นหา">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i
                            class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            {{-- <li class="header">เมนูหลัก</li> --}}
            <li class="active treeview">
                <a href="#">
                    <i class="fa fa-folder-open-o"></i> <span>หนังสือเข้า</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    @can('view inbox unreceive menu')
                    <li><a href="{{ route('unreceive.index') }}"><i class="fa fa-circle-o"></i>
                            หนังสือรอลงทะเบียนรับ
                        </a>

                    </li>
                    @endcan

                    @can('view inbox receive menu')
                    <li><a href="{{ route('receive.index') }}"><i class="fa fa-circle-o"></i>
                            หนังสือลงทะเบียนรับแล้ว</a></li>
                    @endcan

                    @can('view inbox reject menu')
                    <li><a href="{{ route('reject.index') }}"><i class="fa fa-circle-o"></i> หนังสือที่ถูกตีกลับ</a>
                    </li>
                    @endcan
                </ul>
            </li>
            <li class="active treeview">
                <a href="#">
                    <i class="fa fa-folder-open-o"></i> <span>หนังสือส่ง</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    @can('view outbox unsend menu')
                    <li><a href="{{ route('unsend.index') }}"><i class="fa fa-circle-o"></i> หนังสือรอลงทะเบียนส่ง
                        </a>
                    </li>
                    @endcan

                    @can('view outbox send menu')
                    <li><a href="{{ route('send.index') }}"><i class="fa fa-circle-o"></i> หนังสือลงทะเบียนส่งแล้ว</a>
                    </li>
                    @endcan

                    @can('view outbox reject-send menu')
                    <li><a href="{{ route('reject-send.index') }}"><i class="fa fa-circle-o"></i>
                            หนังสือที่ถูกตีกลับ</a></li>
                    @endcan
                </ul>
            </li>
            <li class="active treeview">
                <a href="#">
                    <i class="fa fa-search"></i> <span>สืบค้นและรายงานหนังสือ</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">

                    @can('view search menu')
                    <li><a href="{{ route('search') }}"><i class="fa fa-circle-o"></i> สืบค้นหนังสือ</a></li>
                    {{-- <li><a href="index2.html"><i class="fa fa-circle-o"></i> รายงานหนังสือเข้า</a></li>
                    <li><a href="index2.html"><i class="fa fa-circle-o"></i> รายงานหนังสือออก</a></li> --}}
                    @endcan

                </ul>
            </li>

            @can('view admin menu')
            <li class="active treeview">
                <a href="#">
                    <i class="fa fa-cogs"></i> <span>จัดการระบบ</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">

                    @can('view user manage menu')
                    <li><a href="{{ route('user.index') }}"><i class="fa fa-users"></i> จัดการผู้ใช้งานระบบ</a></li>
                    @endcan
                    @can('view role menu')
                    <li><a href="{{ route('role.index') }}"><i class="fa fa-check-circle-o"></i>
                            จัดการบทบาทของผู้ใช้งานระบบ</a></li>
                    @endcan

                </ul>
            </li>
            @endcan

        </ul>
    </section>
    <!-- /.sidebar -->
</aside>